import { motion } from "framer-motion";
import { useEffect, useState } from "react";

export default function Privacy() {
  const [theme, setTheme] = useState<'light' | 'dark'>('dark');

  useEffect(() => {
    const savedTheme = localStorage.getItem('kubegraf-theme') as 'light' | 'dark' | null;
    if (savedTheme) {
      setTheme(savedTheme);
      document.documentElement.setAttribute('data-theme', savedTheme);
    } else if (window.matchMedia && window.matchMedia('(prefers-color-scheme: light)').matches) {
      setTheme('light');
      document.documentElement.setAttribute('data-theme', 'light');
    }
  }, []);

  const toggleTheme = () => {
    const newTheme = theme === 'dark' ? 'light' : 'dark';
    setTheme(newTheme);
    document.documentElement.setAttribute('data-theme', newTheme);
    localStorage.setItem('kubegraf-theme', newTheme);
  };

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Header */}
      <header className="border-b border-white/5 py-4 px-6">
        <div className="max-w-4xl mx-auto flex justify-between items-center">
          <a href="/" className="flex items-center gap-2 font-display font-bold text-xl">
            <img src="/assets/logo/kubegraf_color_icon.png" alt="KubeGraf" className="object-contain" style={{ width: 96, height: 96 }} />
            KubeGraf
          </a>
          <nav className="flex gap-6 text-sm text-muted-foreground">
            <a href="/" className="hover:text-primary transition-colors">Home</a>
            <a href="/docs" className="hover:text-primary transition-colors">Docs</a>
          </nav>
        </div>
      </header>

      {/* Content */}
      <section className="max-w-4xl mx-auto px-6 py-16">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <h1 className="text-4xl md:text-5xl font-display font-bold mb-8">Privacy Policy</h1>

          <div className="prose prose-invert max-w-none space-y-6 text-muted-foreground leading-relaxed">
            <p>
              This policy explains what data KubeGraf collects, how it's used, and what choices you have.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">What data KubeGraf does NOT collect</h2>
            <p>
              KubeGraf runs locally on your machine. Your Kubernetes logs, events, configurations, resource definitions, and cluster metrics never leave your environment. We do not collect, store, or transmit any of this data to any server.
            </p>
            <p>
              We do not use cookies, trackers, analytics platforms, or third-party advertising services on kubegraf.io. We do not profile users or build behavioral datasets.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">What data is collected</h2>
            <p>
              <strong>Free version:</strong> None. KubeGraf Free collects no data.
            </p>
            <p>
              <strong>Pro version:</strong> When you use KubeGraf Pro, the software performs anonymous license verification by sending a license key to our license server. This request does not include cluster data, user identity, or usage patterns. We do not log or retain client IP addresses beyond what is required for basic network operation. It only confirms whether the license is valid.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">How data is used</h2>
            <p>
              License verification requests are used only to validate that a Pro license is active. We do not use this data for analytics, marketing, or user tracking.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">Data storage and retention</h2>
            <p>
              All incident data, logs, and diagnostics generated by KubeGraf are stored locally in SQLite databases on your machine. We do not have access to this data.
            </p>
            <p>
              License verification logs are retained for 90 days for operational purposes, then deleted.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">Third-party services</h2>
            <p>
              KubeGraf does not integrate with third-party analytics, advertising, or tracking services. The Pro license server is operated by us and does not share data with external parties.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">User choices and control</h2>
            <p>
              You control all local data. You can delete SQLite databases, incident histories, or any other data KubeGraf generates at any time by removing the relevant files from your system.
            </p>
            <p>
              If you stop using KubeGraf Pro, license verification requests stop immediately.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">Changes to this policy</h2>
            <p>
              If we change this privacy policy, we will update this page and note the revision date. Continued use of KubeGraf after changes indicates acceptance of the updated policy.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">Contact</h2>
            <p>
              Questions about this policy? Email us at{" "}
              <a href="mailto:contact@kubegraf.io" className="text-primary hover:text-primary/80">
                contact@kubegraf.io
              </a>
            </p>

            <p className="text-sm text-muted-foreground/70 mt-12">
              Last updated: December 19, 2025
            </p>
          </div>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/5 py-8 px-6">
        <div className="max-w-4xl mx-auto text-center text-sm text-muted-foreground">
          <p>&copy; 2025 KubeGraf</p>
        </div>
      </footer>

      {/* Theme Toggle Button */}
      <button
        onClick={toggleTheme}
        className="fixed bottom-8 right-8 w-12 h-12 rounded-full bg-background/80 backdrop-blur-sm border border-white/10 flex items-center justify-center cursor-pointer hover:scale-110 hover:border-primary transition-all duration-300 shadow-lg z-50"
        aria-label="Toggle theme"
      >
        <span className="text-xl">{theme === 'dark' ? '☀️' : '🌙'}</span>
      </button>
    </div>
  );
}
